### ISSUE TITLE
Spamming errors when using top/down arrows and enter

### ISSUE THREAD

**Issue by nikelborm** [charlieroberts/bitty#1]
![Screenshot From 2024-11-20 09-04-57](https://github.com/user-attachments/assets/df246932-30fd-4f70-8207-232a0ed78bfa)

**Comment by charlieroberts** [comment]
thanks! I removed the active line plugin from the demo in f850903 while I debug it. If you have the time to tell me the exact text / keystrokes that started this messages I'd appreciate it, it's pretty hit or miss for me to duplicate.

**Comment by nikelborm** [comment]
hi, just opened the demo again. Errors I mentioned before are not being thrown anymore. I'm not sure how to reproduce it now. That's the keys I meant:
![depositphotos_10723643-stock-photo-arrow-keys-on-keyboard-2869927227|200](https://github.com/user-attachments/assets/b623772c-4b82-43a8-a00d-c97036d4a2b0)

**Comment by nikelborm** [comment]
I did git checkout to the repo version (49c39cf) that was at the moment I created the issue. Getting the same error. I can run some debug code you'll suggest. I'm currently here with running local server and can help

**Comment by nikelborm** [comment]
I created this logger
```js
var testfunc = (eventName) => (e) => {
    console.log(
      'eventName', eventName,
      'keyCodeDEP', e.which,
      'key', e.key,
      'code', e.code,
      'location', e.location
    );
  };
  $0.onkeydown = testfunc('onkeydown');
  $0.onkeypress = testfunc('onkeypress');
  $0.onkeyup = testfunc('onkeyup')
```

**Comment by nikelborm** [comment]
Here is what I get
![Screenshot From 2024-11-21 00-19-22](https://github.com/user-attachments/assets/5ea3bbe0-afa7-459f-b5b5-f8e1152928c8)

**Comment by nikelborm** [comment]
Also every time I click on some line, it gets highlighted forever
![Screenshot From 2024-11-21 00-22-41](https://github.com/user-attachments/assets/4158d248-e323-4356-a5b9-3b39fbc56fc7)

**Comment by charlieroberts** [comment]
I added a page specifically for the active line plugin: 

https://charlieroberts.github.io/bitty/plugins/highlight_active_line.html

... and did some fixes for the plugin as well if you want to test there. It shouldn't spam error messages anymore! I'm still having problems where `<div>`s get nested inside of each other (instead of having one per line as expected) which causes a bunch of bugs and I'll be tackling that next, which might also fix more bugs related to this plugin.

**Comment by nikelborm** [comment]
Hi, thank you for improving it!

There are no errors in the console, bu highlighting is still buggy.
There are several things i noticed:
1. it's possible to click on a special place and everything goes highlighted.
2. it's possible to desync current line with highlighted line. where highlighted line is few positions above or below the cursor
3. it's possible to have highlighted more than one line

I recorded a video for you

**Comment by nikelborm** [comment]
https://github.com/user-attachments/assets/539f425a-b100-4cc0-9f74-101a1d0b98d7

**Comment by nikelborm** [comment]
Also if the first thing you do after page load is clicking below the latest line, not only the whole screen get highlighted, but also it starts spamming errors again, and I catch your debugger statement. Also it's often possible to move around not only using up and down errors, but using right and left errors. Your debugger statement catches me only when I use up and down arrows, but not when i use left and right arrows

**Comment by nikelborm** [comment]
https://github.com/user-attachments/assets/2ee7457c-5928-4e99-a791-7dda35771f9f

**Comment by charlieroberts** [comment]
OK I fixed bug 1 in the most recent commit. Bug 3 is related to placing divs inside of divs, I'm planning to tackle that next. Thanks for all the detailed feedback!

**Comment by nikelborm** [comment]
I tried to open your link https://charlieroberts.github.io/bitty/plugins/highlight_active_line.html
Highlights disappeared completely.
Does it work as intended?

**Comment by nikelborm** [comment]
![Screenshot From 2024-11-26 06-43-49](https://github.com/user-attachments/assets/88154f8e-07df-42dc-b63c-56ed5c2d42b5)

**Comment by nikelborm** [comment]
You forgot `)` here
![Screenshot From 2024-11-26 06-51-56](https://github.com/user-attachments/assets/ae4086cd-71d2-4b77-9331-8981586770ec)

**Comment by charlieroberts** [comment]
hah, well, that syntax error was one way to fix it :) added the parenthesis now though.

**Comment by nikelborm** [comment]
https://github.com/user-attachments/assets/0943c76d-6208-4e11-b036-37f5260e6739

Found few more bugs

1. setting cursor with mouse on the last line doesn't affect highlight
2. I'm able to remove highlight by clicking on the last selected line after clicking on the last line

**Comment by charlieroberts** [comment]
Both those bugs should now be fixed! Also fixed a bug when all code was deleted

**Comment by nikelborm** [comment]
Hey, thank you for quick responses and resolution and thank you for fixing those ❤️
I just tested and the only thing left, that i was able to find, is desyncing of cursor and highlighting.
Key sequences to reproduce:
1. down, left, home, down, left, home
2. down, down, down, end, right, up, end, right, up

https://github.com/user-attachments/assets/5d6a9e14-ffed-4537-a924-d9431ac9c7b4

**Comment by nikelborm** [comment]
I also found quite a few bugs when dealing with selection mechanisms and when selecting something and then returning cursor back etc. At some point i even was able to get 2 lines to be highlighted. A lot of times I was catching highlighting of a piece of text (`line 1`) like you can see on the video:

https://github.com/user-attachments/assets/08425180-d5c6-4e29-b624-4c6aadfab8d1

**Comment by nikelborm** [comment]
If the video is too fast, sorry, i was kinda playfully-competitively trying to break it with different key combinations, if you need I can write key-by-key sequences for those also

**Comment by nikelborm** [comment]
I just think that a lot of those bugs may disappear after you add handling of moving between the lines when using right and left arrows instead of top and bottom, because highlights don't react to them at all

https://github.com/user-attachments/assets/c780b532-5359-4e26-b2df-f221fdb1b9c1

**Comment by nikelborm** [comment]
And here's how to get bug with 2 highlighted lines:
ctrl-a, ctrl+c, left arrow, ctrl+v

https://github.com/user-attachments/assets/712ebbf0-0fd4-4159-847c-d547acf4629a

**Comment by charlieroberts** [comment]
Thanks for all these! The left / right keys now change the active highlight when the cursor moves to a new line. Still need to work on the pasting / selection issues you identified...

**Comment by charlieroberts** [comment]
OK I added a bunch more bug fixes and maybe things are good enough for now? Let me know if there's anything specific you notice and thanks again for all these pointers!

**Comment by nikelborm** [comment]
pressed arrow down, started holding shift, pressed arrow down, pressed arrow down, stopped holding shift, pressed left

https://github.com/user-attachments/assets/c5d59ecf-f53c-4cfe-9c35-5f246b8e66c5

**Comment by nikelborm** [comment]
pressed end, started holding shift, pressed right, stopped holding shift
result: highlight disappeared

after that: pressed down
result: highlight is desynced with current line

after that: pressed end, pressed right
result: current line has highlight, but ghost line is left


https://github.com/user-attachments/assets/e8b80d82-432f-4c39-b3bf-ba3dba5ed7dc

**Comment by nikelborm** [comment]
Also bug: highlight doesn't react in any way on pressing page down and page up navigation keys and easily gets desynced

**Comment by nikelborm** [comment]
honestly I don't know why did you choose to make your life harder, by handling each key individually and storing selection cursor externally

**Comment by nikelborm** [comment]
https://github.com/user-attachments/assets/f8f6f905-e2a4-4f49-b1ef-fe85daf07143

**Comment by nikelborm** [comment]
you can basically add the same listener on all mousedown/click/mouseup, and all keypresses/keydown/keyups, and maybe some other events and always get active selection start and end position. When the positions are equal it means that's it's just a cursor. You have access to the whole text, which means that you can easily find the line your highlight starts on and the line your highlight ends on

And make highlight lines be just `position: relative` div with `z-index:-10`, whose css `top`, `bottom` properties you change on each event

```js
['mousedown', 'mouseup', 'click', 'keydown', 'keyup', 'keypress'].forEach((eventName) => document.getElementsByClassName('bitty-editor')[0].addEventListener(eventName, e => {
  console.log('Caret at: ', e.target.selectionStart, e.target.selectionEnd)
}))
```

**Comment by nikelborm** [comment]
https://stackoverflow.com/questions/2897155/get-cursor-position-in-characters-within-a-text-input-field

**Comment by charlieroberts** [comment]
Thanks! I think you're right... I went down a bit of a rabbit hole here. Given that I almost always use 65% keyboards on laptops, the chance that I'll cover all 100% keyboard combos that could change the active line is probably pretty small. I had thought about simply polling every 50 ms or so to set the active line, but I think just doing it every keystroke / click / paste will work better. I'll try switching to that model. 

fwiw I'm using  `<div contenteditable>` and not a input elements in the project.

**Comment by charlieroberts** [comment]
OK, I made that change.  Definitely simplifies the code quite a bit!

**Comment by nikelborm** [comment]
But is there any benefit in using `contenteditable` instead of tag that follows semantic html standard and intended for editing text? The shenanigans you do everywhere to work with selection cursor seem a bit too much. There are some racing condition stuff is going on, that makes cursor stay on the same line when I press `enter`. With time it will only get harder to make it work stable with `contenteditable`.

If you type `a, s, d, Enter, a, s, d, Enter, a, s, d, Enter, a, s, d, Enter, a, s, d, Enter` you'll see how your input gets processed, but if you quickly enough type something after Enter, the position of the cursor jumps back to the previous line and stays there even if new line is also added

And I'm not pressing `arrow up` here to return back. It does it itself.

https://github.com/user-attachments/assets/71255053-d48f-4b06-9369-be85a7da0679

Conversely if you just use `textarea` there's no such issue

https://github.com/user-attachments/assets/b2165ae1-5d36-4352-a3b1-8bfef26fc89a

**Comment by charlieroberts** [comment]
textarea is intended for plaintext. you can work around this by hiding the textarea and presenting formatted text over the top of it, while still using the textarea for input, but this has problems for mobile use :( and of course you have to keep everything in sync etc.

**Comment by nikelborm** [comment]
> textarea is intended for plaintext. you can work around this by hiding the textarea and presenting formatted text over the top of it, while still using the textarea for input, but this has problems for mobile use :( and of course you have to keep everything in sync etc.

Do you plan on adding anything else other than plaintext? There's not a lot of options left: binary, images, videos, sounds, 3d. //joke

If you need syntax highlighting, you don't have to have two layers. In textarea I was thinking you can use [Highlight Web API](https://developer.mozilla.org/en-US/docs/Web/API/Highlight)

**Comment by charlieroberts** [comment]
> Do you plan on adding anything else other than plaintext? There's not a lot of options left: binary, images, videos, sounds, 3d. //joke

I mean, probably, eventually, with a plugin...  if you're interested check out https://charlieroberts.github.io/annotationsAndVisualizations/ for the types of things along these lines I'm curious about.

Highlight API looks nice!!! But not working in Firefox (at least not at the moment) is a deal-breaker for me, and it doesn't look like it work with textareas (although it does work with `contenteditable` divs...), see https://github.com/w3c/csswg-drafts/issues/4603 for more info.

**Comment by charlieroberts** [comment]
awesome, I think the worst of the issues with the enter key were fixed by @cumhuronat in 61c1abd6150d3b288c6c304e74bbf6ad51e16324; so I'm going to go ahead and close this for now.

**Comment by charlieroberts** [comment]
@nikelborm just a quick note that I've moved to using the CSS Custom Highlight API, as Firefox support was finally added a few weeks ago. Definitely makes things a lot easier than before!

**Comment by nikelborm** [comment]
Cool! :)
